version: "3.2"
services:
  profile-web:
    image: pmutisya/profile:latest
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    restart: always

  profile-server:
    image: pmutisya/profile-server:1.0.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://profile-mysql:3306/profile?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=@SimplePWD1
      - LOGGING_LEVEL_ROOT=INFO
      - "TZ=Africa/Nairobi"
    ports:
      - 8080:8080
    volumes:
      - /apps/media/profile/:/apps/media/
    restart: always

  profile-mysql:
    image: mysql:5.7.18
    volumes:
      - /apps/database/helpdesk/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=@SimplePWD1
      - MYSQL_DATABASE=profile
      - "TZ=Africa/Nairobi"
    ports:
      - 3308:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
    restart: on-failure
